import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
    uz: {
        login: "Kirish",
        register: "Ro'yxatdan o'tish",
        logout: "Chiqish",
        search_placeholder: "Atamani qidirish...",
        composers: "Kompozitorlar",
        dictionary: "Lug'at",
        profile: "Profil",
        instruments: "Cholg'u asboblari",
        virtual_piano: "Virtual Fortepiano",
        metronome: "Metronom",
        bpm: "Tezlik (BPM)",
        start: "Boshlash",
        stop: "To'xtatish",
        admin_info: "Ma'lumotlarni boshqarish",
        admin_desc: "Tizimdagi barcha ma'lumotlar Google Sheets orqali boshqariladi. Yangilash uchun quyidagi tugmani bosing.",
        open_sheets: "Google Jadvalni ochish",
        footer_contact: "Bog'lanish",
        footer_resources: "Resurslar",
        footer_heritage: "Musiqiy Meros",
        footer_news: "Yangiliklar",
        footer_address_label: "Toshkent sh., Olmazor tumani, Universitet ko'chasi, 7-uy",
        footer_subscribe_placeholder: "E-mail kiritishingiz",
        footer_rights: "Barcha huquqlar himoyalangan",
        footer_privacy: "Maxfiylik siyosati",
        footer_subscribe_success: "Obunaga rahmat! Tez orada yangiliklarni yuboramiz.",
        footer_news_text: "Yangi musiqa atamalar va musiqiy tadbirlar haqida xabardor bo'ling.",
        fullname: "To'liq ismingiz",
        username: "Foydalanuvchi nomi",
        password: "Parol",
        submit: "Tasdiqlash",
        loading: "Yuklanmoqda...",
        error_empty: "Jadval bo'sh yoki yuklanmadi.",
        error_fetch: "Jadvalni yuklab bo'lmadi.",
        no_results: "Hech narsa topilmadi",
        trending: "Ko'p qidirilgan:",
        theme_dark: "Tungi rejim",
        theme_light: "Kunduzgi rejim",
        listen: "Eshitish",
        home: "Bosh sahifa",
        have_account: "Hisobingiz bormi?",
        no_account: "Hisobingiz yo'qmi?",
        enter: "Kirish",
        register_action: "Ro'yxatdan o'tish",
        term_def_label: "Izoh",
        quiz: "Viktorina",
        start_quiz: "Viktorinani boshlash",
        quiz_title: "Musiqiy bilimingizni sinab ko'ring",
        quiz_question: "Savol",
        quiz_correct: "To'g'ri!",
        quiz_wrong: "Noto'g'ri!",
        quiz_result: "Natija",
        quiz_restart: "Qayta urinish",
        quiz_level_expert: "Musiqa Professori",
        quiz_level_advanced: "Musiqachi",
        quiz_level_beginner: "Hovaskor",
        term_of_the_day: "KUN ATAMASI",
        read_more: "Batafsil ma'lumot",
        composers_title: "Mashhur Kompozitorlar",
        registration_success_message: "Muvaffaqiyatli ro'yxatdan o'tdingiz!",
        registration_error_message: "Ro'yxatdan o'tishda xatolik yuz berdi.",
        login_or_password_incorrect: "Login yoki parol noto'g'ri",
        system_error_occurred: "Tizimda xatolik yuz berdi",
        welcome_portal: "Xush kelibsiz! Musiqa lug'ati portali",
        site_title: "Virtual Musiqa Lug'ati",
        site_subtitle: "Musiqiy bilimlar manbai",
        sidebar_news: "Musiqa Dunyosida",
        daily_quote: "Musiqa — so'z bilan aytib bo'lmaydigan tuyg'ular sadosi.",
        news_1: "Shashmaqom xalqaro festivali yakunlandi",
        news_2: "Yangi simfonik orkestr tashkil etildi"
    },
    ru: {
        login: "Вход",
        register: "Регистрация",
        logout: "Выйти",
        search_placeholder: "Поиск термина...",
        composers: "Композиторы",
        dictionary: "Словарь",
        profile: "Профиль",
        instruments: "Музыкальные инструменты",
        virtual_piano: "Виртуальное пианино",
        metronome: "Метроном",
        bpm: "Темп (BPM)",
        start: "Старт",
        stop: "Стоп",
        admin_info: "Управление данными",
        admin_desc: "Все данные в системе управляются через Google Sheets. Нажмите кнопку ниже для перехода.",
        open_sheets: "Открыть Google Таблицу",
        footer_contact: "Контакты",
        footer_resources: "Ресурсы",
        footer_heritage: "Музыкальное Наследие",
        footer_news: "Новости",
        footer_address_label: "г. Ташкент, Алмазарский район, ул. Университетская, 7",
        footer_subscribe_placeholder: "Введите ваш E-mail",
        footer_rights: "Все права защищены",
        footer_privacy: "Политика конфиденциальности",
        footer_subscribe_success: "Спасибо за подписку! Скоро мы отправим вам новости.",
        footer_news_text: "Будьте в курсе новых музыкальных терминов и событий.",
        fullname: "Полное имя",
        username: "Имя пользователя",
        password: "Пароль",
        submit: "Подтвердить",
        loading: "Загрузка...",
        error_empty: "Таблица пуста или не загружена.",
        error_fetch: "Не удалось загрузить таблицу.",
        no_results: "Ничего не найдено",
        trending: "Популярные:",
        theme_dark: "Ночной режим",
        theme_light: "Дневной режим",
        listen: "Прослушать",
        home: "Главная",
        have_account: "Есть аккаунт?",
        no_account: "Нет аккаунта?",
        enter: "Войти",
        register_action: "Зарегистрироваться",
        term_def_label: "Описание",
        quiz: "Викторина",
        start_quiz: "Начать викторину",
        quiz_title: "Проверьте свои знания о музыке",
        quiz_question: "Вопрос",
        quiz_correct: "Правильно!",
        quiz_wrong: "Неправильно!",
        quiz_result: "Результат",
        quiz_restart: "Попробовать снова",
        quiz_level_expert: "Профессор музыки",
        quiz_level_advanced: "Музыкант",
        quiz_level_beginner: "Любитель",
        term_of_the_day: "ТЕРМИН ДНЯ",
        read_more: "Подробнее",
        composers_title: "Известные Композиторы",
        registration_success_message: "Вы успешно зарегистрировались!",
        registration_error_message: "Ошибка при регистрации.",
        login_or_password_incorrect: "Неверный логин или пароль",
        system_error_occurred: "Произошла системная ошибка",
        welcome_portal: "Добро пожаловать в Музыкальный Портал",
        site_title: "Виртуальный музыкальный словарь",
        site_subtitle: "Источник музыкальных знаний",
        sidebar_news: "В Мире Музыки",
        daily_quote: "Музыка — это голос чувств, которые невозможно выразить словами.",
        news_1: "Завершился международный фестиваль Шашмаком",
        news_2: "Создан новый симфонический оркестр"
    },
    kaa: {
        login: "Kiriw",
        register: "Dizimnen o'tiw",
        logout: "Shig'iw",
        search_placeholder: "Atamani izlew...",
        composers: "Kompozitorlar",
        dictionary: "Sózlik",
        profile: "Profil",
        instruments: "Musıka ásbapları",
        virtual_piano: "Virtual Fortepiano",
        metronome: "Metronom",
        bpm: "Tezlik (BPM)",
        start: "Baslaw",
        stop: "To'xtatıw",
        admin_info: "Maǵlıwmatlardı basqarıw",
        admin_desc: "Sistemadaǵı barlıq maǵlıwmatlar Google Sheets arqalı basqarıladı. Jańalaw ushın tómendegi túymeni basıń.",
        open_sheets: "Google Kesteni ashıw",
        footer_contact: "Baylanıs",
        footer_resources: "Resurslar",
        footer_heritage: "Musıkalıq Miyras",
        footer_news: "Jańalıqlar",
        footer_address_label: "Tashkent q., Almazar rayonı, Universitet kóshesi, 7-úy",
        footer_subscribe_placeholder: "E-mail kiritwin'iz",
        footer_rights: "Barlıq huqıqlar qorg'algan",
        footer_privacy: "Qupıyalılıq siyasatı",
        footer_subscribe_success: "Obunaga rahmat! Tez arada jan'alıqlardı jiberemiz.",
        footer_news_text: "Jan'a musıka atamaları hám musıkalıq ilajlar haqqında xabardar bolın'.",
        fullname: "Tolıq atıńız",
        username: "Paydalanıwshı ati",
        password: "Parol",
        submit: "Tastıyıqlaw",
        loading: "Jüklennpekte...",
        error_empty: "Keste bos yamasa jüklennbedi.",
        error_fetch: "Kesteni jüklep bolmadı.",
        no_results: "Hesh nárse tabılmadı",
        trending: "Kóp izlengen:",
        theme_dark: "Túngi rejim",
        theme_light: "Kúndizgi rejim",
        listen: "Tıńlaw",
        home: "Bas bet",
        have_account: "Esabıńız bar ma?",
        no_account: "Esabıńız joq pa?",
        enter: "Kiriw",
        register_action: "Dizimnen o'tiw",
        term_def_label: "Túsindirme",
        quiz: "Viktorina",
        start_quiz: "Viktorinanı baslaw",
        quiz_title: "Musıkalıq bilińizdi sınap kóriń",
        quiz_question: "Soraw",
        quiz_correct: "Durıs!",
        quiz_wrong: "Qáte!",
        quiz_result: "Natiyje",
        quiz_restart: "Qayta urınıs",
        quiz_level_expert: "Musıka Professorı",
        quiz_level_advanced: "Musıkashı",
        quiz_level_beginner: "Hovesker",
        term_of_the_day: "KÚN ATAMASI",
        read_more: "Batafsil maǵlıwmat",
        composers_title: "Belgili Kompozitorlar",
        registration_success_message: "Tabisli dizimnen o'ttińiz!",
        registration_error_message: "Dizimnen o'tiwde qátelik boldı.",
        login_or_password_incorrect: "Login yaki parol qáte",
        system_error_occurred: "Sistemada qátelik boldı",
        welcome_portal: "Xosh keldińiz! Musıka sózligi portalı",
        site_title: "Virtual Musıka Sózligi",
        site_subtitle: "Musıkalıq bilimler deregi",
        sidebar_news: "Musıka Dünyasında",
        daily_quote: "Musıka — sóz benen aytıp bolmaytuǵın tuyǵılar sadosı.",
        news_1: "Shashmaqom xalıqaralıq festivalı juqmaqlandı",
        news_2: "Jańa simfonikalıq orkestr shólkemlestirildi"
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        return localStorage.getItem('appLanguage') || 'uz';
    });

    useEffect(() => {
        localStorage.setItem('appLanguage', language);
    }, [language]);

    const t = (key) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
